### ISSUE TITLE
Возможность полностью удалить сервер из списка серверов

### ISSUE THREAD

**Issue by vosur** [tym32167/arma3beclient#14]
Привет. Как насчет того, чтобы добавить возможность полностью удалить сервер из списка серверов? Пусть даже с подчисткой всех данных из БД, которые относятся к этому серверу? Скопилось много серверов, которые уже не нужны

**Comment by tym32167** [comment]
Взял в работу

**Comment by tym32167** [comment]
Если будешь удалять сервер с большой историей, то это займет достаточно времени (у меня минут 10 ушло)

**Comment by tym32167** [comment]
Вместе с сервером удалятся:
1. Чат этого сервера
2. Баны этого сервера
3. История посещений юзером
4. Админы этого сервера

**Comment by tym32167** [comment]
Необходимо быть внимательным, так как по нажатию "сохранить" процесс удаления уже не остановить.

**Comment by tym32167** [comment]
Выполнено. Вошло в релиз 5.5. Тикет закрываю.
