### ISSUE TITLE
[UI] Возможность управлять причинами бана/кика/временем бана непосредственно из UI

### ISSUE THREAD

**Issue by hia3project** [tym32167/arma3beclient#15]
На текущий момент шаблоны для кика или бана содержат очень странные причины, которые крайне сложно применять на практике. Наше сообщество поддерживает работу сразу нескольких публичных серверов с высоким онлайном и постоянным притоком новых игроков. Команда наших администраторов, использующая исключительно программу arma3beclient, регулярно сталкивается с необходимостью применения санкций к игрокам, но испытывает колоссальные трудности с указанием причин. Предлагаю их актуализировать.

Мы предлагаем на рассмотрение следующий готовый список:
Teamkilling - повторяющееся случайное или намеренное убийство дружественных игроков
Spamming - спам в голосовой или текстовый чат
Cheating - использование уязвимостей игры, жульничество
Hacking - взлом игры
Insulting - пренебрежение к игрокам и администрации, издевательство, насмехательство
Microphone Jam - ненамеренное заедание микрофона
Bad Language - сквернословие (может не быть намеренным, но неприемлемо частым)
Bad Nickname - некорректный ник
Advertising - реклама сторонних ресурсов
Sabotage - саботирование игры, призыв к бойкоту, призыв уйти на другой сервер
Inadequate - бессвязный бред, опьянение, прочие причины, сводящие поведение в неадекватность

В случае рассмотрения предложения готов активно отвечать на вопросы и озвучивать коллективные ответы от наших админов.

**Comment by tym32167** [comment]
@CHUIk , я очень рад, что нашу программу используют не только в рамках нашего проекта. В скором времени я снова займусь её доработкой\разработкой, потому мне очень важна обратная связь от пользователей. 
Я внимательно читаю все запросы, потому если у вас или у вашей команды будут пожелания или предложения, то вы всегда можете мне создать подобный тикет и я его рассмотрю. 
Что касается причин бана\кика. На данный момент в файле конфигурации рядом с исполняемым файлом (Arma3BEClient.exe.config) есть ключи для указания своих причин бана\кика (ключи называются Ban_reasons и Kick_reasons - https://github.com/tym32167/arma3beclient/blob/master/src/Arma3BE.Client/App.config#L33). Сами причины там разделены вертикальной чертой ("|"). Я понимаю, что это не очень удобно для пользователя и такой функционал был добавлен таким способом, так как его требовалось реализовать быстро и с минимальными усилиями. Таким образом, на данный момент вы можете сами своими силами настроить нужные вам причины кика или бана.
Тем не менее, я тикет оставлю открытым, так как в планах есть возможность изменения причин бана\кика непосредственн в программе, не изменяя вручную никакие файлы, и хранить эти причины непосредственно в локальной БД. 
На последок, не забудьте скачать и попробовать последнюю версию, если этого ещё не сделали https://github.com/tym32167/arma3beclient/releases/latest

**Comment by hia3project** [comment]
Благодарю за оперативный ответ. Было бы здорово увидеть в программе описанный Вами функционал.

**Comment by tym32167** [comment]
@CHUIk Да, но я не обещаю это сделать скоро, так как это не блокирует работу с программой, а изменить причины бана\кика у вас есть возможность и примо сейчас самостоятельно.

**Comment by hia3project** [comment]
Уже занялся этим. Спасибо за помощь в нахождении метода добавления собственных причин бана/кика.

**Comment by tym32167** [comment]
related to #18

**Comment by tym32167** [comment]
Включено в ближайший релиз

**Comment by tym32167** [comment]
Предполагаю, что шаблоны в результате этого тикета будут храниться в БД.

**Comment by tym32167** [comment]
Тикет закрываю, функционал добавлен в текущую сборку. На странице настроек добавил вкладку с редактируемыми гридами. Также обновил выбиралку времени бана при бане игрока.  Знаю, что выглядит не супер, но работает. Сборку можно скачать отсюда https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.237-develop/artifacts Будут предложения/пожелания - велком.
