### ISSUE TITLE
[Запрос функционала] Возможность назначать перманентные баны

### ISSUE THREAD

**Issue by hia3project** [tym32167/arma3beclient#16]
Функционал стандартного RCON включает в себя возможность назначать бессрочные баны. Описание команд на официальном сайте:

ban [player #] [time in minutes] [reason]
Ban a player’s BE GUID from the server. If time is not specified or 0, the ban will be permanent. Optionally you can also display a reason.

Мы с нетерпением ждём появления этой функции в arma3beclient.

**Comment by tym32167** [comment]
Для перманентного (бессрочного) бана достаточно указать время бана, равное 0. 
![ban_perm](https://cloud.githubusercontent.com/assets/610799/16671429/ae0f03b4-449f-11e6-9b3b-650619e0ce3e.PNG)

**Comment by tym32167** [comment]
@CHUIk проверьте пожалуйста работоспособность данного функционала (не забудьте скачать последнюю версию программы https://github.com/tym32167/arma3beclient/releases/latest ), и отпишите результаты. Если все хорошо, то я закрою тикет.

**Comment by hia3project** [comment]
Я понял. Тогда немного перефразирую суть тикета. Шаблоны времени бана, имеющиеся на текущий момент сложны для восприятия большинством наших админов. Буду говорить именно о нашем сообществе.Я уже понял, что backend у программы отличный, но frontend местами очень желательно видоизменить. Этот тикет действительно можно закрывать. Но я сейчас оформлю другой.

**Comment by tym32167** [comment]
Закрыто, так как фукнционал уже есть.
