### ISSUE TITLE
Обновление списка игроков препятствует работе

### ISSUE THREAD

**Issue by hia3project** [tym32167/arma3beclient#17]
Обновление списка игроков препятствует работе с той частью списка, которая требует использования ползунка для прокрутки. При этом обновление списка происходит будто бы с разной частотой. Иногда случается по 2 обновления в секунду, а в другой раз бывает, что обновлений вообще как будто нет. Вообще, было бы замечательно иметь в Настройках программы параметр "время обновления списка игроков в секундах". Такая опция есть в подавляющем большинстве RCON-клиентов.

**Comment by tym32167** [comment]
@CHUIk В данный момент обновление списка происходит только если игрок вышел с сервера\зашел на сервер. То есть, если никто долго не выходит и не заходит, обновления не происходит вовсе. Если Заходят\выходят часто - обновление происходит часто. 
Вообще я думал над тем, чтобы обновлять по таймеру. 
Тикет оставлю, подумаю насчет настройки с частотой обновления. Спасибо!

**Comment by hia3project** [comment]
На нашем флагманском сервере длительное время удерживается высокий онлайн. А самое главное, это описанная мной ранее частота присоединения и отсоединения игроков. Теперь я понимаю, что именно по этой причине наши админы порой физически не в состоянии оперативно оформить бан или кик. Прокрученный ими список постоянно сбрасывается в начало и они так могут секунд по 30 сидеть и раз раз разом безрезультатно прокручивать список. Мы все будем крайне признательны, если алгоритм обновления хотя бы начнёт учитывать событие OnMouseButtonDown, относящееся к полосе прокрутки. В этот момент программа могла бы задержать процесс обновления списка до события OnMouseButtonUp. Или же обновление по времени решило бы проблему. Но от себя я хочу отметить, что обновление списка, причиной которого является именно событие (вход/выход с сервера), то для серверов с высоким траффиком (например нашим) эта схема всё же более удобна и рациональна. Проблему решила бы задержка обновлений при использовании пользователем ползунка прокрутки.

**Comment by tym32167** [comment]
Хорошо, я подумаю что с этим можно сделать

**Comment by hia3project** [comment]
Благодарю за внимание к моей просьбе!

**Comment by tym32167** [comment]
Включено в ближайший релиз

**Comment by tym32167** [comment]
fixed in 0.5.6 release

**Comment by tym32167** [comment]
@hia3project проблема будет исправлена в следующем релизе. Предлагаю побыть моими тестерами и попробовать свежую сборку программы. Сборка может быть не стабильной. Ссылка на сборку https://dl.dropboxusercontent.com/u/38076493/arma3/Arma3BEClient.zip

**Comment by hia3project** [comment]
Благодарю! С огромным удовольствием опробуем!

**Comment by tym32167** [comment]
Обновил сборку. В старой были проблемы с баном игрока, что уже вышел с сервера. 
Новую сборку можно скачать тут https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.226-develop/artifacts

**Comment by tym32167** [comment]
Вроде проблем с тикетом нет, закрываю.
