### ISSUE TITLE
[Запрос функционала] Возможность редактировать шаблоны времени бана и назначать текстовое описание, вместо числового отображения.

### ISSUE THREAD

**Issue by hia3project** [tym32167/arma3beclient#18]
Существующие шаблоны для назначения времени бана было бы замечательно увидеть также в конфиг-файле, чтобы была возможность задать название шаблона для указанного временного интервала. Например:

`<add key="Ban_durations" value= [0,"Permanent Ban"] | [60,"One Hour Ban"] | [1440,"One Day Ban"] | [4320,"Three Days Ban"] | [10080,"One Week Ban"] | [40320,"One Month Ban"] />`

**Comment by tym32167** [comment]
Включено в ближайший релиз

**Comment by hia3project** [comment]
Отличная новость, благодарю за внимание!

**Comment by tym32167** [comment]
Тикет закрываю, функционал добавлен в текущую сборку. На странице настроек добавил вкладку с редактируемыми гридами. Также обновил выбиралку времени бана при бане игрока.  Знаю, что выглядит не супер, но работает. Сборку можно скачать отсюда https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.237-develop/artifacts Будут предложения/пожелания - велком.
