### ISSUE TITLE
Интерфейс для настройки обновления списка игроков

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#21]
У пользователя должна быть возможность выбрать вариант обновления списков Игроков/Админов/Банов

Варианты обновления:
1. По таймеру
2. При входе/выходе игрока / админа

**Comment by hia3project** [comment]
Повторю своё предложение чуть, выдвинутое ранее - задержка обновления при входе/выходе вовремя нажатия ЛКМ на ползунке (ползунках) прокрутки.

**Comment by tym32167** [comment]
В задержке нет необходимости, поглядите как это сейчас работает в сборке из
тикета #17

**Comment by tym32167** [comment]
@hia3project 
@oDenZeL
Прошу отписать, есть ли ещё такая проблема и действительно ли нужны такие настройки на обновление списка игроков? Банов? Админов?  ( проблема отписана в тикете #17  )

**Comment by tym32167** [comment]
готово, добавил натройку, билд тут https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.247-develop/artifacts
