### ISSUE TITLE
[UI] Часовой пояс

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#31]
Хотелось бы видеть в настройках выбор часового пояса, т.к. прибавлять постоянно 3 часа не охота.

**Comment by tym32167** [comment]
Резонно. Это можно. Я посмотрю, будет ли у меня возможность включить это в релиз. Если не в ближайший, то в следующий.

**Comment by tym32167** [comment]
Добавлено в ближайший релиз.

**Comment by tym32167** [comment]
Задача готова, добавил опцию в настройки, ссылка на билд https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.243-develop/artifacts
