### ISSUE TITLE
[UI] Возможность получить STEAM ID игрока

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#34]
Возможно ли реализовать копирование PID'a игрока?

**Comment by tym32167** [comment]
Что именно ты хочешь скопировать и откуда? Расскажи подробнее, я не понял
вопроса.

**Comment by oDenZeL** [comment]
Есть такая штука как PID - player ID, он совпадает с ID steam аккаунта и если была бы возможность копировать данный id, можно без проблем получить информацию о steam профиле игрока.
PID отображается в настройках профиля ARMA3 вроде.

**Comment by oDenZeL** [comment]
Еще нашел вот такую вот интересную штуку https://forums.bistudio.com/topic/175216-online-steam-id-to-battleye-guid-converter/

Только в нашем случае требуется наоборот конвертировать.

**Comment by tym32167** [comment]
Перевести из ид стима в гуид игрока я и сам могу. Проблема в том, что это
перевод в одну сторону. Из гуида игрока ид стима уже не получить. В теории
можно попробовать извернуться, но это требует много вычислений и не уверен,
что стим будет рад, если кто то будет получать ид игроков по их гуидам. У
меня даже есть тикет для этого #28, но я не уверен, что эта фича настолько
востребована, чтобы разбираться с этим.

**Comment by ToxaBes2** [comment]
Конвертацию Battleye id в Steam id не сделать т.к. battleye id это md5 hash от steam id, а хешерование это операция в одну сторону.

**Comment by ToxaBes2** [comment]
> В теории можно попробовать извернуться

нет, подбор по rainbow tables тут не поможет, т.к. там не только md5 но и промежуточные вычисления.

**Comment by tym32167** [comment]
Я уже находил 99% наших игроков в стиме, это примерно 60тыс. Так что все
реально, только долго и надо ли?

**Comment by ToxaBes2** [comment]
Расскажи как делал? Нагенерил предварительно свой гиганский массив вида steam_id => battleye_id  и искал по нему?

**Comment by tym32167** [comment]
да, именно так, самый тупой способ. Взял свой ид, прибавил 300 миллионов
(или 30 лямов.. не помню сколько) и отнял 300 миллионов и прошелся по 600
миллионам записей. Хранить это месиво мне смысла не было, я искал
конкретные 60 тыс гуидов, и почти все нашел.

**Comment by ToxaBes2** [comment]
Даже если взять только +/- 30 млн, даже если учесть что ты используешь MS SQL Compact в качестве БД, простая таблица ключ => значение может получится по размеру больше чем вся программа. Под такое есть смысл делать отдельный сервис/прогу.

**Comment by tym32167** [comment]
Возможно, если планируешь хранить всю таблицу. Я ничего хранить не хочу. Да
и какой сервис, если у меня сервака нет.

**Comment by tym32167** [comment]
Еще до конца недопилено и не протестировано, но концепт работает и позволяет отыскивать игроков в стиме. Пока добавил закладку к открытому серверу. Как сейчас использовать: открываем вкладку с сервером, переходим на Steam Discovery, нажимаем Start. Как только найденных плееров будет примерно 8тыс, жмем стоп, ждем, снова старт. И так до 100%. Знаю, неудобно, но времени на большее сегодня не было. Билд можно скачать тут https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/artifacts , БД старая автоматом проапгрейдится для хранения ИД стима игрока. Сам этот ИД будет доступен на форме информации о игроке. @ToxaBes если интересно, глянь сорсы, как я это делаю, хотя код там не очень и ещё поменяется :) 
У меня среди 60439 игроков нашло 60055 (99,36%)

**Comment by ToxaBes2** [comment]
Отличное решение! Зачем хранить базу всех возможных игроков если интересуют только те игроки которые уже есть в базе программы. Кому нужно, тот будет периодически заполнять в своей базе id-шки. Сорцы глянул, спасибо.
