### ISSUE TITLE
[UI] [Analysis] Нестандартные каналы связи

### ISSUE THREAD

**Issue by 12st** [tym32167/arma3beclient#43]
Арма позволяет создавать и настраивать свои собственные каналы для голосового\текстового общения. Однако программа такие каналы не видит, из-за этого порой возникают проблемы. Есть ли возможность их подключить?

**Comment by tym32167** [comment]
@12st Спасибо, совсем забыл про это. Проведу анализ, попробую пофиксить, если смогу. Включено в ближайший релиз.

**Comment by tym32167** [comment]
Результаты теста - все нестандартные каналы отмечены как unknown, Пример:

> (Unknown) ToxaBes: тест для тима

Планирую отмечать их отдельным цветом в чате

**Comment by tym32167** [comment]
Готово, скачать билд можно тут https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.254-develop/artifacts

**Comment by 12st** [comment]
Протестировал, все работает. Цвет думаю таким можно и оставить, привыкаешь быстро.

**Comment by tym32167** [comment]
Отлично, спасибо!
