### ISSUE TITLE
[UI] Возможность видеть, кто заходил/выходил с сервера

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#45]
Возможность для быстрого бана игрока, что уже вышел с сервера.

**Comment by tym32167** [comment]
Добавлена новая вкладка для входов / выходов игроков
![issue_45](https://cloud.githubusercontent.com/assets/610799/19215279/9113f72c-8d99-11e6-8d59-b95fe83dc7ba.png)

Ссылка на билд: https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.5.5.259-develop/artifacts

**Comment by tym32167** [comment]
@oDenZeL , @12st , @hia3project Если есть возможность, поглядите на фичу. Хочу понять, нужна она или нет.

**Comment by ToxaBes2** [comment]
@tym32167 - меня то за что? )

**Comment by tym32167** [comment]
@ToxaBes Так надо ж было кого-нить забанить, а забанить тебя на твоем сервере вдвойне смешнее :)

**Comment by 12st** [comment]
Протестил, всё работает нормально, очень удобная штука однозначно надо оставлять.

**Comment by tym32167** [comment]
@12st Окей, спасибо. Тогда тикет закрываю, это войдет в ближайший релиз.
