### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#48]
Можно ли реализовать функционал привязки к базе данных на хостинге?
В принципе, это решает многие проблемы.

**Comment by tym32167** [comment]
1. Проблема раз: сейчас в БД пишется оч много - это не тлько игроки, но и история их входов, айпишники, ники, история подключения админов, игровой чат и тд + список серверов с паролями в открытом виде. Это не только небезопасно хранить на хостинге, но и все подключенные админы увидят все сервера.
2.  Это, в теории, можно хранить на хостинге, но только в том случае, если в одно время к нему будет подключена только 1 программа. Если подключить 2 программы, чат и все истории будут писаться в БД дважды. 3 программы - трижды, и тд.
3. Технически можно, если БД на хостинге одна из этих
- MySQL Connector/NET
- System.Data.SQLite
- Oracle Data Provider for .NET
- VistaDB
- Devart
- cdata
- OpenLink Software
- IBM
- Sybase SQL Anywhere
- Sybase Adaptive Server Enterprise
- Phoenix Software Solutions
- Synergex
- Firebird
- Npgsql
- NuoDB
- Ritmo for IBM i (DB2)

Как итог: все писать на хостинг нельзя, максимум - список серверов и список игроков. Если этого достаточно, то я подумаю о возможности такой настройки. Никакого чата, историй входов и прочего, что мжет быть добавлено автоматически (даже комментарий для игрока, он обновляется автоматом), хранить на хостинге не получится.

**Comment by tym32167** [comment]
> В принципе, это решает многие проблемы.

Какие проблемы?

**Comment by oDenZeL** [comment]
Проблемы, относительно организации администрирования, а не программы :)

**Comment by tym32167** [comment]
Если проблемы не касаются программы, но я не могу помочь, Тикет закрываю.
