### ISSUE TITLE
[UI] Глюк при установке миссии на сервере

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#55]
Есть еще глюк при установке миссии на сервере. Выбираю миссию и жму set mission и выдает Can't find a mission collection / mission with template name: 'название миссии', skipping to next mission.
После может запуститься миссия с другим названием. Но это может у бисов глюк.

**Comment by 12st** [comment]
На серверах под линуксом оно вообще крашит сервер.

**Comment by tym32167** [comment]
Краш сервера - это уже чисто серверная проблема. На UI я на это повлиять не могу никак.

**Comment by ToxaBes2** [comment]
>На серверах под линуксом оно вообще крашит сервер.

>Краш сервера - это уже чисто серверная проблема


С сервером все ок. Крашится что-то внутри армы, т.е. процесс остается висеть, он не зомби, но на команды больше не реагирует, приходится перезапускать процесс.

**Comment by ToxaBes2** [comment]
https://forums.bistudio.com/topic/188037-rented-arma-3-linux-server-no-way-to-change-mission-without-reboot-server/

Скорее всего ребята правы, это косяк самой сборки армы под Linux.

**Comment by tym32167** [comment]
@ToxaBes спасибо. Осталось проверить аналогичное на win хостинге. Но, есть ощущение, что это чисто серверная проблема на любом хостинге.

**Comment by tym32167** [comment]
http://www.tehgam.com/showthread.php?t=814&page=5&p=15542&viewfull=1#post15542
> По поводу set mission. Когда этой функции не было в проге я юзал одно время другой BE клиент и там миссии ставились. Здесь же с самого начала она работала как-то рандомно - то ставит, то нет. Если в чате написать #vote mission, #mission или #missions то ничего не происходит. Как будто не уходит команда на сервер. Но я это особо не тестил.

**Comment by ToxaBes2** [comment]
@tym32167  - ты случайно смену миссии на сервере сегодня не тестил?

**Comment by tym32167** [comment]
@ToxaBes  Неа, но вчера попробовал рестарт сервера на рф2, и повесил их сервак

**Comment by ToxaBes2** [comment]
>Can't find a mission collection / mission with template name: 'название миссии'

Возможно чтобы эта ошибка ушла нужно заполнить [Mission_rotation](https://community.bistudio.com/wiki/server.cfg#Mission_rotation) в server.cfg. На первом сейчас эти поля не используются.

**Comment by ToxaBes2** [comment]
Бампану немного эту старую тему. Из BE клиента не получится нормально сменить миссию или перезапустить сервер если арма работает на Linux сервере. Просто потому что сервер армы запускается отдельным скриптом (обычно bash) в котором определяются все необходимые переменные окружения и ключи запуска. 
Даже если зайти в лобби админом и выбрать другую миссию из списка - она запустится, но потеряется используемый arma3profile (настройки сложности). 
Предложение следующее: проверять через BE тип сервера. Если os != w то скрывать в интерфейсе возможность смены миссии и перезапуска сервера.

**Comment by tym32167** [comment]
@ToxaBes  Тут 2 важных аспекта
1) Через BE не проверить тип OS. Это можно сделать только через Steam Query. 
2) Я бы не хотел отслеживать когда бисы нормально это пофиксят. Сегодня у них одно не работает, завтра другое. 

Я бы мог добавить настройку, какие кнопки управления сервером юзеру показывать, но это придется настраивать для каждого сервера отдельно, что не очень удобно. 
По сути ты предлагаешь фиксить проблемы сервера в клиентской проге. Я понимаю, что юзеру так будет удобней, но это как то неправильно :)

**Comment by ToxaBes2** [comment]
Клиентская прога на моей памяти ложила сервер раз пять, последний раз не так давно. Именно поэтому я предлагаю убрать эту возможность. БИСы никогда не пофиксят это под линукс просто потому что это behaviour by design. Можно ли делать Steam Query для определения ОС при запуске программы или открытии вкладки с сервером?

**Comment by ToxaBes2** [comment]
Ну или предупреждение можно добавить. Вида: "Вы уверены что хотите ... На Linux системах это приведет к падению Arma 3 сервера!".

**Comment by tym32167** [comment]
@ToxaBes  Вот в таком виде сделал
![image](https://user-images.githubusercontent.com/610799/39775289-b9188f82-52fd-11e8-8427-2cc3b02266cf.png)
Команды подсвечиваются: выбор миссии, shutdown, restart и restart server. При попытке выполнить команду выдаст предупреждение, что она может не поддерживаться. Сделал это для всех операционок, что не винда. 
Остальные команды работают в прежнем режиме
![image](https://user-images.githubusercontent.com/610799/39775593-ae07210c-52fe-11e8-8056-bb5c3bb4f24a.png)
Для виндовых серваков вообще ничего не изменилось
![image](https://user-images.githubusercontent.com/610799/39775615-c0d5dca6-52fe-11e8-9a79-b4036b799d43.png)

**Comment by tym32167** [comment]
@ToxaBes погляди. Если тебе норм, то я закрою тикет.

**Comment by ToxaBes2** [comment]
Отлично, то что нужно. Спасибо! Тикет можно закрывать.
