### ISSUE TITLE
Переподключение админов

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#60]
http://www.tehgam.com/showthread.php?t=814&p=15542&viewfull=1#post15542
> Еще вопрос - у всех после обновы какой-то (кажется добавили стим порт в ней) два админа в проге? Они переподключаются с интервалом 20-30 мин, меняя порт. При чем более интенсивно на пустом сервере. На полном может висеть значительно более 30 мин 
![image](https://cloud.githubusercontent.com/assets/610799/20642780/7808e7ec-b418-11e6-8940-8c57aeb59554.png)

**Comment by 12st** [comment]
Они висят не по двое, когда обновляешь страницу с админами один исчезает. Просто постоянно идет переподключение с разных портов
![toolwiz201611-26-22-52-5](https://cloud.githubusercontent.com/assets/18305023/20642833/01418ce6-b42b-11e6-9fe3-6e6c1af17ec2.png)

**Comment by tym32167** [comment]
Ага. @12st  спасибо, возможно, ты показал мне где проблема. Дело в том, что я писал защиту от потери соединения, которая, если 5 минут нет сообщений от сервера, переподключается. Похоже, пока переписать тот код :)

**Comment by tym32167** [comment]
@12st Скинь плиз сюда или мне на почту логи от этого времени

**Comment by tym32167** [comment]
Логи для исследования
[Logs.zip](https://github.com/tym32167/arma3beclient/files/614424/Logs.zip)

**Comment by tym32167** [comment]
Проблема осталась, пофиксить не удалось. Причем потери соединения нет. Склоняюсь ко мнению, что это особенности сервера. Тикет закрываю, как не приоритетный.
