### ISSUE TITLE
[UI] возможность отправлять самописные ркон команды

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#63]

**Comment by ToxaBes2** [comment]
В свежем SPOTREP от БИСов появилось:
Added: A new #restartserver Dedicated Server command

Может есть смысл добавить новую кнопку "Restart Server" рядом с кнопками по смене миссий? По нажатию кнопки всплывающее окно с подтверждением "Are you sure?". В этом случае если миссия зависла или багнул рестарт миссии можно перезапустить сам процесс.

**Comment by tym32167** [comment]
@ToxaBes  да, можно. Добавил тикет #64

**Comment by tym32167** [comment]
готово
![image](https://cloud.githubusercontent.com/assets/610799/20854533/13d4a1bc-b8f5-11e6-87a4-6dee282178d9.png)

**Comment by tym32167** [comment]
Список команд тут https://community.bistudio.com/wiki/BattlEye
Дока https://www.battleye.com/support/documentation/

**Comment by tym32167** [comment]
Должно работать, закрываю
