### ISSUE TITLE
Огромный пинг в программе

### ISSUE THREAD

**Issue by 12st** [tym32167/arma3beclient#68]
Уже не в первый раз замечаю, что порой программа отображает просто огромный пинг. Причём у игрока всё просто замечательно. Зависает такой пинг сразу у нескольких клиентов и не обновляется пока программа не будет перезапущена. Сомневаюсь, что это можно исправить, да и не сильно это мешает, но вдруг.  
![toolwiz20171-22-20-20-8](https://cloud.githubusercontent.com/assets/18305023/22186106/5fced3ce-e101-11e6-8dac-3359ac10de92.png)

[log_2017_01_22_19_BELog.txt](https://github.com/tym32167/arma3beclient/files/722274/log_2017_01_22_19_BELog.txt)
[log_2017_01_22_20.txt](https://github.com/tym32167/arma3beclient/files/722275/log_2017_01_22_20.txt)

**Comment by tym32167** [comment]
Спасибо, погляжу. А у других игрокв обновляется?

**Comment by 12st** [comment]
Да, у тех у кого пинг нормальный

**Comment by tym32167** [comment]
если так, то определенно проблема на стороне сервера. Но логи гляну попозжа

**Comment by ToxaBes2** [comment]
В последнее время очень часто кикает людей с сервера якобы по причине Signature check time out. Это общее название ошибки в случае если до клиента не достучаться. Люди вылетают по двое, по трое. Возможен ли вариант что постоянные запросы от программы по BE протоколу начинают подвешивать какую-то подсистему в арме и в результате на ком зависло те и вылетают? Это просто предположение. Можно попробовать не подключаться к серверу программой несколько дней и помониторить результат.

**Comment by 12st** [comment]
С завтрашнего дня не включаю программу, в четверг о результатах сообщим.

**Comment by tym32167** [comment]
Протестил, пинг обновляется. Воспроизвести зависший пинг не получилось. Тикет закрываю.
