### ISSUE TITLE
[UI] Комментирование пользователей

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#69]
Предложение такое. Было бы удобно, если по нажатию на выделенную на скриншоте область, можно было сразу оставлять комментарии.
![2017-01-26_21-34-01](https://cloud.githubusercontent.com/assets/20484713/22345131/f434b6a8-e40f-11e6-8a9d-d812d1a8cde4.png)

**Comment by tym32167** [comment]
Я бы не хотел делать грид редактируемым, он не для этого предназначен. Но я могу открывать инфу о пользователе при двойном клике. Зацени сборку https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/0.7.296/artifacts

**Comment by oDenZeL** [comment]
@tym32167 Работает хорошо!
