### ISSUE TITLE
[UI] Ширина столбцов

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#70]
Возможно сделать автоматическое сохранение ширины столбцов, при изменении их ширины?

**Comment by tym32167** [comment]
Вообще это уже сделано, проверь еще раз. Когда ты устанавливаешь ширину
столбца, потом закрываешь приложение и заново открываешь, ширина должна
быть такой, как ты установил

**Comment by oDenZeL** [comment]
@tym32167 Да, действительно, работает!

**Comment by tym32167** [comment]
Это касается не только ширины, но и порядка столбцов. Единственное, что я
не сохраняю- это сортировку
