### ISSUE TITLE
[UI] Никнеймы в разделе "Блокировки"

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#71]
После переустановки ОС, появилась необходимость в повторной установке RCON'a. Никнеймы в данном разделе не отображаются, как поправить?
![2017-01-27_17-19-31](https://cloud.githubusercontent.com/assets/20484713/22373988/3a0e97b6-e4b5-11e6-8bc6-d4557d211821.png)

**Comment by tym32167** [comment]
Если от предыдущей программы не осталось базы данных, то никак. Ник игрока
сохраняется только если программа его словила на сервере. Так как это
список банов, а забаненые игроки не могут зайти на сервер, ты не узнаешь их
никнеймов
