### ISSUE TITLE
Импорт\экспорт настроек

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#72]
Возможно ли реализовать импорт\экспорт настроек программы? Сервера, расположение\ширина столбцов, шаблоны блокировок?

**Comment by tym32167** [comment]
В папке с программой есть файл, называется Database.sdf, там хранятся все данные, сервера, игроки, настройки. Ты можешь скачать последнюю версию программы отсюда https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/artifacts , распаковать, кинуть туда свой файл от старой программы и запускать - все настройки подхватятся.

**Comment by tym32167** [comment]
@oDenZeL отпиши, это то, что бы хотел? Если да, то тикет закрою

**Comment by oDenZeL** [comment]
@tym32167 Да, в принципе можно закрывать...

**Comment by tym32167** [comment]
ок
