### ISSUE TITLE
[UI] Время блокировка

### ISSUE THREAD

**Issue by oDenZeL** [tym32167/arma3beclient#75]
С чем может быть связано неправильное написание времени блокировки?
На скриншоте 11:55, а на самом деле блокировка состоялась в 15:55.

![2017-02-04_15-15-55](https://cloud.githubusercontent.com/assets/20484713/22618430/fd82a59c-eaec-11e6-8951-f8582f3345a0.png)

**Comment by tym32167** [comment]
время блокировки пишется в UTC
