### ISSUE TITLE
Steam discovery блокирует подключение к steam

### ISSUE THREAD

**Issue by ToxaBes2** [tym32167/arma3beclient#84]
Не знаю, баг это или фича но при запуске steam discovery из программы невозможно включить steam. Пишет что не может подключиться. Пробовал несколько раз.

**Comment by tym32167** [comment]
Steam discovery и вообще вся программа никак не связана со стимом

**Comment by ToxaBes2** [comment]
Мое дело сообщить. Пробовал 3 раза.

**Comment by tym32167** [comment]
С добавлением #91 больше не актуально
