### ISSUE TITLE
Я извиняюсь но я слишком тупой.

### ISSUE THREAD

**Issue by Vova12421** [tym32167/arma3beclient#86]
Привет.
Я вот не понял как мне сервак добавить ип вожу нечего ип хоста тоже вожу нечего.Я уже 2 дня не могу понять видео или надписи по поводу как его добавить нету. Что где когда нету везде нечего нету.Буду рад если кто то подскажет как

**Comment by tym32167** [comment]
Добрый день.
Спасибо за вопрос. Сервер добавляется в опциях приложения. Нужно указать IP адрес, название сервера, пароль и порты для подключения и стим запросов.

Пример:
![howtoaddserver](https://user-images.githubusercontent.com/610799/30177393-001c1cbc-9406-11e7-9d17-f9856d9b94fc.gif)

Если после этого сервер все равно не подключается, то смотрите что не так с настройками сервера\файервола.

**Comment by ToxaBes2** [comment]
@tym32167 - добавь эту гифку в readme.md файл в новую секцию "Setup example". Думаю, будет полезно для многих пользователям.

**Comment by tym32167** [comment]
@ToxaBes Дельная мысль, сделаю попозжа

**Comment by Vova12421** [comment]
Спасибо
Что делать если дисконект пишет а сервер включен ?

**Comment by tym32167** [comment]
@Vova12421 Проверять порты, правильность указанного пароля, настройки сервера, фейервола.

**Comment by Vova12421** [comment]
Пароль сервера указывать или ркон ?

**Comment by tym32167** [comment]
@Vova12421 Программа подключается по протоколу RCON, потому надо указывать RCON пароль и RCON порт.

**Comment by Vova12421** [comment]
А как узнать ркон порт ?

**Comment by Vova12421** [comment]
Я честно извиняюсь за такие глупые вопросы я первый раз сталкиваюсь с такой программой.

**Comment by Vova12421** [comment]
А всё разобрался

**Comment by Vova12421** [comment]
Спасибо за помощь

**Comment by tym32167** [comment]
Пожалуйста :) 
Тикет закрываю.
