### ISSUE TITLE
Обновить Readme - добавить описание и пару сценариев использования

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#87]
по мотивам https://github.com/tym32167/arma3beclient/issues/86#issuecomment-327883744

**Comment by tym32167** [comment]
#86

**Comment by Vova12421** [comment]
Я извиняюсь а Arma3BEClient может ли работать без BattlEye или он обязательный ?

**Comment by tym32167** [comment]
Обязательный. По сути программа подключается не к серверу Армы, а к серверу Battleye.

**Comment by Vova12421** [comment]
Ясно Спасибо

**Comment by tym32167** [comment]
Обновил readme, добавил пару гифок для начала работы с программой
