### ISSUE TITLE
Какой лучше порт использовать

### ISSUE THREAD

**Issue by Vova12421** [tym32167/arma3beclient#88]
Здравствуйте подскажите какой лучше порт использовать для программы?

**Comment by tym32167** [comment]
Любой, программе нет разницы через какой порт подключаться. Главное, чтобы
сервер был настроен.

**Comment by Vova12421** [comment]
прописал порт в батл еар 2122 он не заходит а когда 2302 он заходит но люди зайти не могут побывал так же менять и открывал по новому

**Comment by tym32167** [comment]
Так это касается настройки сервера. Программе, как клиенту, нужен только коннект к службе battleye, на каком она порту настроена, туда и подключайся.
