### ISSUE TITLE
[UI] Поверх всех окон

### ISSUE THREAD

**Issue by Noart537** [tym32167/arma3beclient#89]
Добавить кнопочку или пункт меню "Поверх всех окон".

**Comment by tym32167** [comment]
Готово, проверяй @Noart537 
![image](https://user-images.githubusercontent.com/610799/34654666-49653a9e-f3ff-11e7-8a73-6b1cd92e4db0.png)

**Comment by tym32167** [comment]
Поправил чуть чуть
![image](https://user-images.githubusercontent.com/610799/34654773-962d09be-f400-11e7-8695-402cd95a48f2.png)

**Comment by Noart537** [comment]
Спасибо, работает.

**Comment by tym32167** [comment]
Отлично, тогда закрываю.
