### ISSUE TITLE
[Запрос функционала] Возможность отправлять личные сообщения игрокам

### ISSUE THREAD

**Issue by hia3project** [tym32167/arma3beclient#9]
Функционал стандартного RCON включает в себя возможность отправки приватных сообщений игрокам на сервере. Этой опции критически не хватает в Вашем замечательном приложении. Очень надеюсь её увидеть в приложении arma3beclient. Заранее благодарю!

**Comment by tym32167** [comment]
Привет. Спасибо за предложение. Да, пока такого нет. Я, конечно, запланирую
приватные сообщения, но сроки реализации пока не могу назвать.
9 Мар 2016 г. 14:58 пользователь "CHUIk" notifications@github.com написал:

**Comment by tym32167** [comment]
Обрати внимание, что есть ещё незакрытые баги. Они касаются списка банов и их синхронизации. Если у тебя 1 сервер, то ок. Если несколько, то аккуратней, т.к. последний релиз оказался нестабилен в этом плане

**Comment by tym32167** [comment]
Функционал запланирован, работа по нему начата.

**Comment by tym32167** [comment]
Функционал можно опробовать в пререлизе тут 
https://github.com/tym32167/arma3beclient/releases/tag/0.5.5

**Comment by hia3project** [comment]
Отличные новости. Благодарю за оперативность!

**Comment by tym32167** [comment]
Прошло тестирование. Багов сильных не заметил. Тикет закрываю. Функционал появится в ближайшем стабильном релизе. В пререлизе уже доступен.
