### ISSUE TITLE
BE иногда долго восстанавливает соединение и пропускает все команды от админа

### ISSUE THREAD

**Issue by tym32167** [tym32167/arma3beclient#94]
После правок будет:

1) При потере соединения будет автоматическая попытка восстановления (произойдет незамедлительно) + раз в минуту проверка наличия подключения. 
2) При потере соединения во время подключения - произойдет немедленное переподключение. Дается 100 попыток на немедленное переподключение. После 100 попыток подключиться, проверка будет просто раз в минуту, до восстановления подключения
3) Если клиент не подключен, но админ посылает команды, то отправленные команды (до 10 штук) будут выполнены немедленно при подключении
4) При попытке отправить команду неподключенному клиенту будет автоматом выполнена попытка подключения

**Comment by ToxaBes2** [comment]
>При потере соединения во время подключения - произойдет немедленное переподключение. Дается 100 попыток на немедленное переподключение.

Может лучше 60 попыток с таймаутом в 1 сек?

**Comment by tym32167** [comment]
@ToxaBes  Автор библиотеки, которую я использую, просто вызывал Connect() рекурсивно - поэтому при потере сети прога крашилась с переполнением стека. Я сначала убрал рекурсию совсем, и потому при подключении соединение могло потеряться и восстановиться только через минуту. Я хочу этого избежать, потому вернул рекурсию, но со счетчиком (надеюсь. автор примет мой пулл реквест с этим) - но если за 100 немедленных попыток соединение не восстановится, то и через секунду скорее всего не станет лучше, потому следующая проверка будет уже в течение минуты.

**Comment by ToxaBes2** [comment]
Я вот о чем имел ввиду: одно соединение это несколько этапов, таких как DNS resolving, TTFB (time to first byte) и другие.  В нормальном состоянии сети это занимает миллисекунды. При восстановлении соединения это может занять более нескольких секунд. Поэтому я и предложил 60 попыток с задержкой в секунду. Как раз получится 1 минута.
Почему с задержкой: если при рекурсивном вызове все падало по SO то значит что не было предусмотрено ожидание результата предыдущего вызова или таймаута. Нет смысла 100 раз стрелять в первые 1-2 сек после потери соединения. Лучше стрелять каждую секунду в течении первой минуты, потом раз в минуту.

**Comment by tym32167** [comment]
@ToxaBes там код синхронный. То есть если резолвинг занимает 5 секунд, то одна попытка будет идти 5 секунд, потом снова попытка на 5 секунд и тд, пока не восстановится или не пройдет 100 попыток. Я просто почему не хочу делать интервалы - для коннекта с интервалами в течение минуты, мне надо либо фризить всю программу на минуту, либо добавлять асинхронщины\многопоточности, что займет много работы. Потому давай поглядим, как оно сейчас будет работать - если все будет ок, то так и оставлю. Будут проблемы - буду чинить.

**Comment by ToxaBes2** [comment]
Понял. Если есть ожидание завершения предыдущей попытки то действительно нет смысла городить огород.

**Comment by tym32167** [comment]
за день ни вылетов, ни потери соединения. Закрываю тикет
