### ISSUE TITLE
Индикация запроса игроков

### ISSUE THREAD

**Issue by ToxaBes2** [tym32167/arma3beclient#95]
Просто идея, которая кажется интересной.

У нас есть полноценный чат для общения с игроками не заходя в игру. Но нет уведомления о том что игроки зовут админа. Опишу суть идеи: в настройках сервера на стороне программы добавляется новое поле, условно "Маркер вызова админа". Допустим мы поставили значение "!ADMIN!".
Затем я в server.cfg пишу серверные сообщения которые видят игроки: 
```sqf
motdInterval = 120;
motd[]={
    "Для вызова админа напишите в чат !ADMIN!",
    "Злоупотребление вызовом админа приведет к кику с сервера",    
};
```

Если игроку нужно позвать админа по какой-либо причине. он просто пишет в чат:
`!ADMIN! миссия не завершается, все облазили`

Программа у админа находит подстроку !ADMIN! в сообщении и начинает мигать в панели задач (по типу как в мессенджерах новое сообщение приходит). 

Дополнение: возможность сворачивать программу в tray чтобы она мигала уже там.

**Comment by tym32167** [comment]
Подобное уже есть, нзывается в настройках Important Words
![image](https://user-images.githubusercontent.com/610799/40269820-91d87ffc-5b83-11e8-882f-c4f0f424e9e5.png)
При попадании такого слова в чате, все сообщение выделяется более жирным
![image](https://user-images.githubusercontent.com/610799/40269829-ad170658-5b83-11e8-9ec8-d315e9134ed5.png)
Я добавил флешинг (чтобы если окно свернуто - моргало при появлении такого слова)
![flashing](https://user-images.githubusercontent.com/610799/40269864-2898974c-5b84-11e8-88ce-f9eb7aa3736c.gif)
Но с треем пока не хочу связываться, это немного муторно :) Будет критично - сделай отдельный тикет на это.

**Comment by ToxaBes2** [comment]
О, круть!

**Comment by tym32167** [comment]
@ToxaBes правда, оно ищет не просто вхождения, а именно слова. То есть оно не отреагирует на aminu \ admina\ karadmin и тд. Таким образом, important word может состоять только из букв, так как при поиске вхождения алгоритм сначала выделит из чата слова (без знаков препинания), а потом уже будет сопоставлять с тем, что ты укажешь. То есть если в чат написать !admin!, то после извлечения слов из чата, получится одно слово admin - и его и будет с настройками сопоставлять. Зато при сопоставлении игнорируется регистр, так что Админ и админ считай одно и то же слово.

**Comment by tym32167** [comment]
@ToxaBes  отпиши, если тебе все ок, то я закрою тикет

**Comment by ToxaBes2** [comment]
Можешь собрать версию со всеми последними изменениями? У меня сейчас нет возможности из исходников собирать.

**Comment by tym32167** [comment]
@ToxaBes  Тебе не надо ничего собирать. Либо в программе обновись 
![image](https://user-images.githubusercontent.com/610799/40278312-0fed5bf0-5c2f-11e8-92fa-f758c5c3a371.png)
либо самая свежая версия всегда доступна на [билд сервере](https://ci.appveyor.com/project/ArtemMuradov/arma3beclient/build/artifacts)

**Comment by ToxaBes2** [comment]
Все работает, спасибо! Тикет можно закрывать.
